language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - sudo apt-get install wireless-tools
install:
  - sudo python setup.py -q install
# command to run tests
script: sudo python setup.py test
